# Generated by Django 4.2.4 on 2024-03-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_data', '0005_participant_groups_semester_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='assistants_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='groups_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='modules_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='participants_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
