# Generated by Django 4.2.4 on 2024-03-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_data', '0006_laboratory_assistants_count_laboratory_groups_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='semester',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='scheduling_data.semester'),
        ),
    ]
