# Generated by Django 4.2.4 on 2024-03-22 08:13

from django.db import migrations, models
import scheduling_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_data', '0009_alter_assistant_prefered_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='prefered_schedule',
            field=models.JSONField(default=scheduling_data.models.default_schedule),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='regular_schedule',
            field=models.JSONField(default=scheduling_data.models.default_schedule),
        ),
        migrations.AlterField(
            model_name='participant',
            name='regular_schedule',
            field=models.JSONField(default=scheduling_data.models.default_schedule),
        ),
    ]
