# Generated by Django 4.2.4 on 2024-03-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_data', '0010_alter_assistant_prefered_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='ipk',
            field=models.FloatField(default=0),
        ),
    ]
