# Generated by Django 5.0.3 on 2024-04-13 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_data', '0012_solution_scheduledata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledata',
            old_name='day_of_week',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='scheduledata',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='best_solution',
        ),
        migrations.AlterField(
            model_name='solution',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
