# Generated by Django 5.0.3 on 2024-04-13 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_data', '0013_rename_day_of_week_scheduledata_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledata',
            name='process_data',
        ),
        migrations.AddField(
            model_name='scheduledata',
            name='solution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_data', to='scheduling_data.solution'),
            preserve_default=False,
        ),
    ]
